### ISSUE TITLE
No source code

### ISSUE THREAD

**Issue by Arafat245** [abrarShariar/Number-Converter-App#2]
I am watching just dll...there is no source code!!!!

**Comment by abrarShariar** [comment]
This repo is for hosting the release version. You will find the source code in the following repo: 
[Source Code](https://github.com/abrarShariar/NumConverter)

**Comment by Arafat245** [comment]
Please mention that in README.

**Comment by abrarShariar** [comment]
Thank you for indicating , I am adding it to README
